#!/bin/bash
SEPARATOR='--------------------------------------------------------------------------------'
VHOSTS_CONFIG_LOCATION="/etc/apache2/sites-available"
exitWithError () {
	MSG=${1}
	if [ -z "$1" ]
	then
		MSG='more attributes needed!'
	fi
	echo -e "\n$SEPARATOR\n\t$MSG\n$SEPARATOR\n\n"
	exit 1
}

# usage: askUser QUESTION ON_YES ON_NO
askUser () {
	if [ -z "$3" ]
	then
		exitWithError #require all arguments or exit with error
	fi

	while true; do
		read -p "${1} [yes/no] " yn
	    case $yn in
	        [Yy]* ) ${2}; break;;
	        [Nn]* ) ${3}; break;;
	        * ) echo "Please answer yes or no.";;
	    esac
	done
}

#-------------------------------------------------------------------------------
TESTFILE="$VHOSTS_CONFIG_LOCATION/000-default.conf"
[ -w $TESTFILE ] || exitWithError 'Need write permissions for vhosts!'

#-------------------------------------------------------------------------------
#ask user about the wanted configuration
arg1 () {
	IS_PROXY=1
}
askUser "Is this a Proxy-VHost?" arg1 break

if [ ! -z "$IS_PROXY" ] && [ "$IS_PROXY" -eq 1 ]
then
	arg1 () {
		PROXY_IGNORE_SSL=1
	}
	askUser "Ignore SSL-Warnings from Proxied Server?" arg1 break
fi

read -p 'Domain Name: ' DOMAIN_NAME
read -p 'Domain aliases (separated by semicolons; empty if none): ' DOMAIN_ALIASES
read -p 'Administration Email: ' ADMIN_EMAIL

if [ -z "$IS_PROXY" ] #only if not a proxy
then
	read -p 'Document Root: ' DOC_ROOT
fi

select type in "HTTP only" "HTTPS only" "both" "forward HTTP to HTTPS"
do
	case $type in
		"HTTP only" )
			USE_HTTP=1
			break;;
		"HTTPS only" )
			USE_HTTPS=1
			break;;
		"both" )
			USE_HTTP=1
			USE_HTTPS=1
			break;;
		"forward HTTP to HTTPS" )
			USE_HTTP="forward"
			USE_HTTPS=1
			break;;
	esac
done

if [ ! -z "$USE_HTTP" ] && [ "$USE_HTTP" == 1 ]
then
	read -p 'HTTP Port [80]: ' PORT_HTTP
	if [ -z "$PORT_HTTP" ]
	then
		PORT_HTTP=80
	fi
fi

if [ ! -z "$USE_HTTPS" ] && [ "$USE_HTTPS" == 1 ]
then
	read -p 'HTTPS Port [443]: ' PORT_HTTPS
	if [ -z "$PORT_HTTPS" ]
	then
		PORT_HTTPS=443
	fi
fi

arg1 () {
	CUSTOM_SSL_CERTS=1
}
askUser 'Use custom SSL Certificates?' arg1 break
if [ ! -z "$CUSTOM_SSL_CERTS" ]
then
	read -p 'Location of the public key: ' CUSTOM_SSL_CERTS_PUBLIC_KEY
	read -p 'Location of the private key: ' CUSTOM_SSL_CERTS_PRIVATE_KEY
	read -p 'Location of the ca cert (optional): ' CUSTOM_SSL_CERTS_CA
fi

arg1 () {
	ENABLE_HTACCESS=1
}
askUser 'Enable .htaccess files?' arg1 break
arg1 () {
	ENABLE_HTPASSWD=1
}
askUser 'Enable authentication via .htpasswd file?' arg1 break
if [ ! -z "$ENABLE_HTPASSWD" ]
then
	read -p 'Location of the .htpasswd file: ' HTPASSWD_FILE
fi

#-------------------------------------------------------------------------------
#generate vhost settings file
getAliases () {
	if [ ! -z "$DOMAIN_ALIASES" ]
	then
		aliases=$(echo $DOMAIN_ALIASES | tr ";" "\n")
		for alias in $aliases
		do
			allAliases=$(echo -e "$allAliases ${alias//[[:space:]]/}")
		done
		echo -e "${1}ServerAlias$allAliases"
	fi
}
getCertConf () {
	if [ -z "$CUSTOM_SSL_CERTS" ]
	then
		CUSTOM_SSL_CERTS_PUBLIC_KEY="/etc/ssl/certs/ssl-cert-snakeoil.pem"
		CUSTOM_SSL_CERTS_PRIVATE_KEY="/etc/ssl/private/ssl-cert-snakeoil.key"
	fi
	echo -e "\n\t\tSSLEngine on\n" \
 		"\t\tSSLCertificateFile $CUSTOM_SSL_CERTS_PUBLIC_KEY\n" \
		"\t\tSSLCertificateKeyFile $CUSTOM_SSL_CERTS_PRIVATE_KEY\n"
	if [ ! -z "$CUSTOM_SSL_CERTS_CA" ]
	then
		echo -e "\t\tSSLCaCertificateFile $CUSTOM_SSL_CERTS_CA\n"
	fi
}

enableHtaccessIfWanted () {
	if [ ! -z "$ENABLE_HTACCESS" ]
	then
		echo -e "\n${1}<Directory $DOC_ROOT>\n" \
			"${1}\tOptions Indexes FollowSymLinks\n" \
			"${1}\tAllowOverwrite All\n" \
			"${1}\tRequire all granted\n" \
			"${1}</Directory>\n"
	fi
}

SETTINGS=""
case "$USE_HTTP" in
	1 )
		SETTINGS=$(echo -e "$SETTINGS\n" \
			"<VirtualHost *:$PORT_HTTP>\n" \
			"\tServerName $DOMAIN_NAME\n" \
			"$(getAliases "\t")\n" \
			"\tServerAdmin $ADMIN_EMAIL\n" \
			"\tDocumentRoot $DOC_ROOT\n" \
			"$(enableHtaccessIfWanted "\t")\n" \
			"\n\tErrorLog \${APACHE_LOG_DIR}/error.log\n" \
			"\tCustomLog \${APACHE_LOG_DIR}/access.log combined\n" \
			"</VirtualHost>\n")
		;;
	'forward')
			SETTINGS=$(echo -e "$SETTINGS\n" \
			"<VirtualHost *:$PORT_HTTP>\n" \
			"\tServerName $DOMAIN_NAME\n" \
			"$(getAliases "\t")\n" \
			"\tRedirect 301 / https://$DOMAIN_NAME/\n" \
			"</VirtualHost>\n")
		;;
esac

if [ ! -z "$USE_HTTPS" ]
then
	SETTINGS=$(echo -e "$SETTINGS\n" \
		"<IfModule mod_ssl.c>\n" \
		"\t<VirtualHost *:$PORT_HTTPS>\n" \
		"\t\tServerName $DOMAIN_NAME\n" \
		"$(getAliases "\t\t")\n" \
		"\t\tServerAdmin $ADMIN_EMAIL\n" \
		"\t\tDocumentRoot $DOC_ROOT\n" \
		"$(enableHtaccessIfWanted "\t\t")\n" \
		"\n\t\tErrorLog \${APACHE_LOG_DIR}/error.log\n" \
		"\t\tCustomLog \${APACHE_LOG_DIR}/access.log combined\n" \
		"$(getCertConf)\n" \
		"\t</VirtualHost>\n" \
		"</IfModule>")
fi

#show config to user
echo -e "Preview for $DOMAIN_NAME:\n$SEPARATOR\n$SETTINGS\n$SEPARATOR"

#-------------------------------------------------------------------------------
#install vhost
CONFFILE="$DOMAIN_NAME.conf"
arg1 () {
	write_file () {
		#TODO write content to file
		echo -e $SETTINGS > "$VHOSTS_CONFIG_LOCATION/$CONFFILE"
	}
	ask_new_filename () {
		read -p 'New name for configuration file: ' CONFFILE
		CONFFILE="$CONFFILE.conf"
		arg1 #retry writing config with new filename
	}
	if [ -s "$CONFFILE" ]
	then
		echo "'$DOMAIN_NAME.conf'does already exist."
		askUser 'Overwrite file?' write_file ask_new_filename
	else
		write_file
	fi
}
askUser "Save configuration?" arg1 exit

arg1 () {
	a2ensite "$CONFFILE" > /dev/null
}
askUser "enable new virtual host?" arg1 exit

arg1 () {
	systemctl restart apache2.service
}
askUser "restart webserver to activate virtual host now?" arg1 exit
