#!/bin/bash

NANO_OPTIONS="--tabsize=4 --constantshow --autoindent --linenumbers --mouse"
NANO_CMD="nano $NANO_OPTIONS"

FILE="$1"
DIR=$(dirname "$1")

if [ -w "$FILE" ] || ( [ ! -f "$FILE" ] && [ -w "$DIR" ] ); then
		exec $NANO_CMD "$1"
elif [ $UID -ne 0 ]; then
		exec sudo $0 $@
else
		echo "Error: Can't edit this file even with root permissions..."
		exit -1
fi
