#!/bin/bash

source ~/.config/darlor/telegram-config

if [ $# -ge 2 ]
then
	screen -dmS sheduled-telegram-msg bash -c "sleep ${2}; ${0} \"${1}\""
else
	if [ $# -eq 0 ]; then
		while read LINE; do MSG="$MSG
$LINE"; done
	else
		MSG="${1}"
	fi
	curl --silent --request GET \
		--url "https://api.telegram.org/bot$BOT_KEY/sendMessage" \
		--data-urlencode "chat_id=$CHAT_ID" \
		--data-urlencode "text=${MSG:0:4096}" > /dev/null
fi
