#!/bin/bash

source ~/.config/darlor/telegram-config

if [ $# -ge 2 ]
then
	screen -dm bash -c "sleep ${2}; ${0} \"${1}\""
else
	curl --silent --request GET \
		--url "https://api.telegram.org/bot$BOT_KEY/sendMessage" \
		--data-urlencode "chat_id=$CHAT_ID" \
		--data-urlencode "text=${1}" > /dev/null
fi
